name: Release Builds

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Get OpenList Latest Version
        id: op_version
        run: |
          OP_VERSION=$(git ls-remote --tags --sort="v:refname" https://github.com/OpenListTeam/OpenList.git | tail -n1 | sed 's#.*/##')
          if [[ ! $OP_VERSION == v* ]]; then
            echo "Failed To Get OpenList Latest Version" >&2
            exit 1
          fi
          echo "OpenList Latest version : $OP_VERSION"
          echo "OP_VERSION=$OP_VERSION" >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run ci
        env:
          MOE_VERSION: ${{ github.ref_name }}
          OP_VERSION: ${{ steps.op_version.outputs.OP_VERSION }}

      - name: Deploy To Dist Branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: dist
          clean: true
          git-config-name: "github-actions[bot]"
          git-config-email: "github-actions[bot]@users.noreply.github.com"
          commit-message: "🏗️ build(dist): ${{ github.ref_name }}"

      - name: Prepare Release Assets
        run: |
          mkdir -p release
          cd dist
          tar -czf "../release/OpenList-Moe-${{ github.ref_name }}.tar.gz" css js
          zip -qr "../release/OpenList-Moe-${{ github.ref_name }}.zip" css js

      - name: Update Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            dist/css/OpenList-Moe.min.css
            dist/js/OpenList-Moe.min.js
            release/OpenList-Moe-${{ github.ref_name }}.tar.gz
            release/OpenList-Moe-${{ github.ref_name }}.zip
